# Generated by Django 2.1 on 2018-08-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblplattform',
            options={'managed': True, 'ordering': ['tf_technische_plattform'], 'verbose_name': 'Plattform', 'verbose_name_plural': '07 Plattform-Übersicht (tblPlattform)'},
        ),
        migrations.AlterUniqueTogether(
            name='qryf3rechteneuvonimportduplikatfrei',
            unique_together={('userid', 'tf', 'enthalten_in_af', 'tf_technische_plattform', 'gf')},
        ),
        migrations.AlterUniqueTogether(
            name='tblrechteamneu',
            unique_together={('userid', 'tf', 'enthalten_in_af', 'tf_technische_plattform', 'gf')},
        ),
        migrations.AlterUniqueTogether(
            name='tblrollen',
            unique_together={('rollenname', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='tbluserhatrolle',
            unique_together={('userid', 'rollenname')},
        ),
    ]
