# Generated by Django 2.2.1 on 2019-07-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhattbluseridundname',
            name='rollen',
            field=models.ManyToManyField(default=None, null=True, related_name='applied_rollen', to='rapp.TblAppliedRolle'),
        ),
    ]
