# Generated by Django 2.1 on 2018-09-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20180827_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgesamt',
            name='userid_name',
            field=models.ForeignKey(db_column='userid_und_name_id', on_delete=django.db.models.deletion.CASCADE, related_name='userIDen', to='rapp.TblUserIDundName'),
        ),
    ]
