# Generated by Django 2.2.1 on 2019-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20190726_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhattbluseridundname',
            name='rollen',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='applied_rollen', to='rapp.TblAppliedRolle'),
        ),
    ]
