# Generated by Django 2.1 on 2018-09-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_auto_20180902_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbluseridundname',
            unique_together={('userid', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='tbluseridundname',
            index_together={('geloescht', 'name', 'userid')},
        ),
    ]
