# Generated by Django 2.2.1 on 2019-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_auto_20190726_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_rights_update',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
