# Generated by Django 2.2.1 on 2019-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_user_last_rights_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhattbluseridundname',
            name='delete_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='deleted_applied_rollen', to='rapp.TblAppliedRolle'),
        ),
        migrations.AddField(
            model_name='userhattbluseridundname',
            name='transfer_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='transfered_applied_rollen', to='rapp.TblAppliedRolle'),
        ),
        migrations.AlterField(
            model_name='userhattbluseridundname',
            name='rollen',
            field=models.ManyToManyField(blank=True, default=None, related_name='applied_rollen', to='rapp.TblAppliedRolle'),
        ),
    ]
