# Generated by Django 2.1 on 2018-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_auto_20180902_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluseridundname',
            name='rolle',
            field=models.ManyToManyField(through='rapp.TblUserhatrolle', to='rapp.TblRollen'),
        ),
    ]
