# Generated by Django 2.1 on 2018-09-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_tbluseridundname_rolle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbluseridundname',
            old_name='rolle',
            new_name='rollen',
        ),
    ]
