# Generated by Django 2.2.1 on 2019-08-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0006_auto_20190809_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbluebersichtafgfs',
            name='tfs',
        ),
        migrations.CreateModel(
            name='TblGfHatTF',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('gf_id', models.ForeignKey(db_column='gf_id', on_delete=django.db.models.deletion.CASCADE, to='rapp.TblUebersichtAfGfs')),
                ('tf_id', models.ForeignKey(db_column='tf_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='rapp.TblGesamt')),
            ],
        ),
    ]
