# Generated by Django 2.2.1 on 2019-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0007_auto_20190814_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluebersichtafgfs',
            name='tfs',
            field=models.ManyToManyField(default=None, related_name='model_gf_hat_tfs', through='rapp.TblGfHatTF', to='rapp.TblGesamt'),
        ),
    ]
