# Generated by Django 2.1 on 2018-09-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0007_remove_tbluseridundname_rollen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblrollehataf',
            name='einsatz',
            field=models.IntegerField(db_column='einsatz', default=0),
        ),
    ]
