# Generated by Django 2.1 on 2018-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0008_tblrollehataf_einsatz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrollehataf',
            name='dv',
        ),
        migrations.RemoveField(
            model_name='tblrollehataf',
            name='nurxv',
        ),
        migrations.RemoveField(
            model_name='tblrollehataf',
            name='xabcv',
        ),
        migrations.AlterField(
            model_name='tblrollehataf',
            name='einsatz',
            field=models.IntegerField(choices=[(0, 'nicht zugewiesen'), (1, 'Nur DV-User'), (2, 'XV, AV, BV, CV-User'), (4, 'nur DV-User'), (8, 'AV, BV, CV-User')], db_column='einsatz', default=0),
        ),
    ]
