# Generated by Django 2.2.1 on 2019-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0009_auto_20190626_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblafliste',
            name='on_delete_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblafliste',
            name='on_transfer_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblgesamt',
            name='on_delete_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblgesamt',
            name='on_transfer_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblrollen',
            name='on_delete_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblrollen',
            name='on_transfer_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbluebersichtafgfs',
            name='on_delete_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbluebersichtafgfs',
            name='on_transfer_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbluseridundname',
            name='on_delete_list',
            field=models.BooleanField(default=False),
        ),
    ]
