# Generated by Django 2.1 on 2018-09-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0009_auto_20180910_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblrollehataf',
            name='afname',
        ),
    ]
