# Generated by Django 2.1 on 2018-09-11 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0010_remove_tblrollehataf_afname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserhatrolle',
            name='letzte_aenderung',
            field=models.DateTimeField(db_column='letzte_aenderung', db_index=True, default=datetime.datetime(2018, 9, 11, 20, 53, 32, 447225, tzinfo=utc)),
        ),
    ]
