# Generated by Django 2.2.1 on 2019-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0010_auto_20190627_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblafliste',
            name='gfs',
            field=models.ManyToManyField(default=None, to='rapp.TblUebersichtAfGfs'),
        ),
        migrations.AddField(
            model_name='tbluebersichtafgfs',
            name='tfs',
            field=models.ManyToManyField(default=None, to='rapp.TblGesamt'),
        ),
    ]
