# Generated by Django 2.1 on 2018-09-13 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0011_auto_20180911_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrollen',
            name='datum',
            field=models.DateTimeField(blank=True, db_column='datum', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tbluserhatrolle',
            name='letzte_aenderung',
            field=models.DateTimeField(blank=True, db_column='letzte_aenderung', db_index=True, default=django.utils.timezone.now),
        ),
    ]
