# Generated by Django 2.2.1 on 2019-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0011_auto_20190627_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblafliste',
            name='del_gfs',
            field=models.ManyToManyField(default=None, related_name='del_gfs', to='rapp.TblUebersichtAfGfs'),
        ),
        migrations.AddField(
            model_name='tblrollen',
            name='del_afs',
            field=models.ManyToManyField(default=None, related_name='del_afs', to='rapp.TblAfliste'),
        ),
        migrations.AddField(
            model_name='tbluebersichtafgfs',
            name='del_tfs',
            field=models.ManyToManyField(default=None, related_name='del_tfs', to='rapp.TblGesamt'),
        ),
        migrations.AddField(
            model_name='tbluseridundname',
            name='del_rollen',
            field=models.ManyToManyField(default=None, related_name='del_rollen', to='rapp.TblRollen'),
        ),
    ]
