# Generated by Django 2.1 on 2018-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0012_auto_20180913_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrollehataf',
            name='einsatz',
            field=models.IntegerField(choices=[(0, 'nicht zugewiesen'), (1, 'Nur DV-User'), (2, 'XV, AV, BV, CV-User'), (4, 'nur XV-User'), (8, 'AV, BV, CV-User')], db_column='einsatz', default=0),
        ),
    ]
