# Generated by Django 2.2.1 on 2019-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0012_auto_20190910_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblappliedaf',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblappliedgf',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblappliedrolle',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblappliedtf',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
