# Generated by Django 2.2.1 on 2019-09-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0013_auto_20190910_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequests',
            name='compare_user_hat_userid_name_cobination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='compare_userid', to='rapp.UserHatTblUserIDundName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changerequests',
            name='requesting_user_hat_userid_name_cobination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_userid', to='rapp.UserHatTblUserIDundName'),
            preserve_default=False,
        ),
    ]
