# Generated by Django 2.1 on 2018-10-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0014_auto_20181003_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrechteneuvonimport',
            name='tf_name',
            field=models.CharField(blank=True, db_column='TF Name', max_length=150, null=True),
        ),
    ]
