# Generated by Django 2.2.1 on 2019-09-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0014_auto_20190912_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changerequests',
            old_name='compare_user_hat_userid_name_cobination',
            new_name='compare_user_hat_userid_name_combination',
        ),
        migrations.RenameField(
            model_name='changerequests',
            old_name='requesting_user_hat_userid_name_cobination',
            new_name='requesting_user_hat_userid_name_combination',
        ),
    ]
