# Generated by Django 2.2.1 on 2019-09-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0015_auto_20190912_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequests',
            name='compare_user_hat_userid_name_combination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_userid', to='rapp.UserHatTblUserIDundName'),
        ),
        migrations.AlterField(
            model_name='changerequests',
            name='requesting_user_hat_userid_name_combination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_userid', to='rapp.UserHatTblUserIDundName'),
        ),
    ]
