# Generated by Django 2.1 on 2018-10-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0016_auto_20181004_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='vip_kennzeichen',
            field=models.CharField(blank=True, db_column='vip', db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='zufallsgenerator',
            field=models.CharField(blank=True, db_column='zufallsgenerator', db_index=True, max_length=32, null=True),
        ),
    ]
