# Generated by Django 2.1 on 2018-10-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0017_auto_20181005_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgesamt',
            name='vip_kennzeichen',
            field=models.CharField(blank=True, db_column='vip', max_length=32, null=True, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='zufallsgenerator',
            field=models.CharField(blank=True, db_column='zufallsgenerator', max_length=32, null=True, verbose_name='Zufallsgenerator'),
        ),
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='vip_kennzeichen',
            field=models.CharField(blank=True, db_column='vip', max_length=32, null=True, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='zufallsgenerator',
            field=models.CharField(blank=True, db_column='zufallsgenerator', max_length=32, null=True, verbose_name='Zufallsgenerator'),
        ),
    ]
