# Generated by Django 2.2.1 on 2019-09-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0017_tbltf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblappliedtf',
            name='model_tf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rapp.TblTf'),
        ),
        migrations.AlterField(
            model_name='tblgfhattf',
            name='tf_id',
            field=models.ForeignKey(db_column='tf_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='rapp.TblTf'),
        ),
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='tfs',
            field=models.ManyToManyField(default=None, related_name='model_gf_hat_tfs', through='rapp.TblGfHatTF', to='rapp.TblTf'),
        ),
    ]
