# Generated by Django 2.2.1 on 2019-09-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0018_auto_20190924_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSchreibweisen',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('schreibweise', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tbltf',
            name='tf_schreibweisen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rapp.TblSchreibweisen'),
        ),
    ]
