# Generated by Django 2.1 on 2019-01-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0018_auto_20181007_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldb2',
            name='geloescht',
        ),
    ]
