# Generated by Django 2.2.1 on 2019-09-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0019_auto_20190925_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltf',
            name='tf_schreibweisen',
        ),
        migrations.AddField(
            model_name='tblschreibweisen',
            name='tf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rapp.TblTf'),
        ),
    ]
