# Generated by Django 2.1 on 2019-01-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0019_remove_tbldb2_geloescht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldb2',
            name='creator',
            field=models.CharField(db_column='CREATOR', default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='tbldb2',
            name='datum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbldb2',
            name='grantee',
            field=models.CharField(db_column='grantee', default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='tbldb2',
            name='grantor',
            field=models.CharField(db_column='GRANTOR', max_length=15),
        ),
        migrations.AlterField(
            model_name='tbldb2',
            name='source',
            field=models.CharField(db_column='source', default='none', max_length=8),
        ),
    ]
