# Generated by Django 2.2.1 on 2019-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0020_auto_20190925_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblschreibweisen',
            name='tf',
        ),
        migrations.AddField(
            model_name='tbltf',
            name='tf_schreibweise',
            field=models.ManyToManyField(default=None, to='rapp.TblSchreibweisen'),
        ),
    ]
