# Generated by Django 2.1 on 2019-01-26 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0020_auto_20190120_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACF_Rechte',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=4, null=True)),
                ('group', models.CharField(db_index=True, max_length=10)),
                ('ressource_class', models.CharField(db_column='class', max_length=16, null=True)),
                ('profil', models.CharField(db_index=True, max_length=128, null=True)),
                ('access', models.CharField(max_length=16, null=True)),
                ('test', models.IntegerField()),
                ('produktion', models.IntegerField()),
                ('alter_control_update', models.IntegerField()),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'RACF-Rechte',
                'verbose_name_plural': '54 RACF - Berechtigungen',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
