# Generated by Django 2.1 on 2019-01-26 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0021_racf_rechte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orga_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abteilungsnummer', models.CharField(db_index=True, max_length=32, null=True)),
                ('organisation', models.CharField(db_index=True, max_length=100)),
                ('orgaBezeichnung', models.CharField(db_index=True, max_length=100, null=True)),
                ('fk', models.CharField(db_index=True, max_length=32, null=True)),
                ('kostenstelle', models.CharField(max_length=32, null=True)),
                ('orgID', models.IntegerField(db_index=True, null=True)),
                ('parentOrga', models.CharField(db_index=True, max_length=32, null=True)),
                ('parentOrgID', models.IntegerField(null=True)),
                ('orgaTyp', models.CharField(max_length=32, null=True)),
                ('fkName', models.CharField(max_length=32, null=True)),
                ('delegationEigentuemer', models.CharField(max_length=32, null=True)),
                ('delegationFK', models.CharField(max_length=32, null=True)),
                ('datum', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Orga-Details',
                'verbose_name_plural': '55 Orga - Details',
                'ordering': ['id', 'organisation', 'orgID', 'parentOrga', 'fkName'],
                'managed': True,
            },
        ),
    ]
    def apply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()

    def unapply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()