# Generated by Django 2.1 on 2019-01-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0022_orga_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racf_rechte',
            options={'managed': True, 'ordering': ['id', 'profil'], 'verbose_name': 'RACF-Rechte', 'verbose_name_plural': '54 RACF - Berechtigungen'},
        ),
    ]
