# Generated by Django 2.2.1 on 2019-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0022_auto_20190925_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltf',
            name='tf_schreibweise',
            field=models.ManyToManyField(default=None, through='rapp.TblTfHatSchreibweise', to='rapp.TblSchreibweisen'),
        ),
    ]
