# Generated by Django 2.2.6 on 2019-10-16 13:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0023_tbltf_tf_schreibweise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuelle_Berechtigung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ersteller', models.CharField(max_length=50, null=True)),
                ('letzte_aenderung', models.DateTimeField(default=django.utils.timezone.now)),
                ('statisch', mdeditor.fields.MDTextField()),
                ('relativ', mdeditor.fields.MDTextField()),
                ('verbundene_af', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rapp.TblAfliste')),
            ],
            options={
                'verbose_name': 'Manuell nachzuhaltenede Berechtigung',
                'verbose_name_plural': '10_Manuell nachzuhaltenede Berechtigungen',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
