# Generated by Django 2.1 on 2019-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0024_auto_20190126_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letzter_import',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('user', models.CharField(max_length=100, null=True)),
                ('end', models.DateTimeField(null=True)),
                ('max', models.IntegerField()),
                ('aktuell', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Letzter Import',
                'verbose_name_plural': 'Letzte Importe',
                'ordering': ['id', 'start', 'end'],
                'managed': True,
            },
        ),
    ]
    def apply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()

    def unapply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()