# Generated by Django 2.1 on 2019-02-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0026_letzter_import_schritt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letzter_import',
            name='schritt',
            field=models.IntegerField(default=1),
        ),
    ]
    def apply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()

    def unapply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()