# Generated by Django 2.1 on 2019-03-16 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0027_auto_20190223_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modellierung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement', models.CharField(db_index=True, max_length=50, null=True)),
                ('neue_beschreibung', models.CharField(max_length=500, null=True)),
                ('plattform', models.CharField(db_index=True, max_length=30, null=True)),
                ('gf', models.CharField(db_index=True, max_length=50)),
                ('beschreibung_der_gf', models.CharField(max_length=500, null=True)),
                ('af', models.CharField(db_index=True, max_length=50)),
                ('beschreibung_der_af', models.CharField(max_length=500, null=True)),
                ('organisation_der_af', models.CharField(max_length=100, null=True)),
                ('eigentuemer_der_af', models.CharField(max_length=100, null=True)),
                ('aus_modellierung_entfernen', models.CharField(max_length=100, null=True)),
                ('datei', models.CharField(max_length=100, null=True)),
                ('letzte_aenderung', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
