# Generated by Django 2.1 on 2019-04-20 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0028_modellierung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direktverbindungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=30)),
                ('entscheidung', models.CharField(max_length=30, null=True)),
                ('entitlement', models.CharField(db_index=True, max_length=100)),
                ('applikation', models.CharField(max_length=20, null=True)),
                ('instanz', models.CharField(max_length=20, null=True)),
                ('identitaet', models.CharField(db_index=True, max_length=50)),
                ('manager', models.CharField(max_length=100, null=True)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100, null=True)),
                ('typ', models.CharField(max_length=100, null=True)),
                ('nicht_anmailen', models.CharField(max_length=8, null=True)),
                ('ansprechpartner', models.CharField(max_length=100, null=True)),
                ('letzte_aenderung', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Direktverbindungen',
                'verbose_name_plural': '61_Direktverbindungen',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='modellierung',
            options={'managed': True, 'verbose_name': 'Modellierung AF GF TF', 'verbose_name_plural': '60_Modellierung AF GF TF'},
        ),
        migrations.AlterUniqueTogether(
            name='direktverbindungen',
            unique_together={('entitlement', 'account_name')},
        ),
    ]
