# Generated by Django 2.1 on 2019-03-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0028_modellierung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modellierung',
            options={'managed': True, 'verbose_name': 'Modellierung AF GF TF', 'verbose_name_plural': '60_Modellierung AF GF TF'},
        ),
    ]
