# Generated by Django 2.0.7 on 2018-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblGesamt',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tf', models.CharField(db_column='TF', max_length=150)),
                ('tf_beschreibung', models.CharField(blank=True, db_column='TF Beschreibung', max_length=150, null=True)),
                ('enthalten_in_af', models.CharField(blank=True, db_column='Enthalten in AF', max_length=150, null=True)),
                ('tf_kritikalitaet', models.CharField(blank=True, db_column='TF Kritikalität', max_length=150, null=True)),
                ('tf_eigentuemer_org', models.CharField(blank=True, db_column='TF Eigentümer Org', max_length=150, null=True)),
                ('gf', models.CharField(blank=True, db_column='GF', max_length=150, null=True)),
                ('vip_kennzeichen', models.CharField(blank=True, db_column='VIP Kennzeichen', max_length=150, null=True)),
                ('zufallsgenerator', models.CharField(blank=True, db_column='Zufallsgenerator', max_length=150, null=True)),
                ('af_gueltig_ab', models.DateTimeField(blank=True, db_column='AF Gültig ab', null=True)),
                ('af_gueltig_bis', models.DateTimeField(blank=True, db_column='AF Gültig bis', null=True)),
                ('direct_connect', models.CharField(blank=True, db_column='Direct Connect', max_length=8, null=True)),
                ('hoechste_kritikalitaet_tf_in_af', models.CharField(blank=True, db_column='Höchste Kritikalität TF in AF', max_length=150, null=True)),
                ('gf_beschreibung', models.CharField(blank=True, db_column='GF Beschreibung', max_length=150, null=True)),
                ('af_zuweisungsdatum', models.DateTimeField(blank=True, db_column='AF Zuweisungsdatum', null=True)),
                ('datum', models.DateTimeField(db_column='Datum')),
                ('geloescht', models.IntegerField(blank=True, db_column='gelöscht', null=True)),
                ('gefunden', models.IntegerField(blank=True, null=True)),
                ('wiedergefunden', models.DateTimeField(blank=True, null=True)),
                ('geaendert', models.IntegerField(blank=True, db_column='geändert', null=True)),
                ('neueaf', models.CharField(blank=True, db_column='NeueAF', max_length=50, null=True)),
                ('nicht_ai', models.IntegerField(blank=True, db_column='Nicht AI', null=True)),
                ('patchdatum', models.DateTimeField(blank=True, db_column='Patchdatum', null=True)),
                ('wertmodellvorpatch', models.TextField(blank=True, db_column='WertModellVorPatch', null=True)),
                ('loeschdatum', models.DateTimeField(blank=True, db_column='löschdatum', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblGesamt',
            },
        ),
        migrations.CreateModel(
            name='TblOrga',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('team', models.CharField(blank=True, db_column='Intern - extern', max_length=150, null=True, unique=True)),
                ('themeneigentuemer', models.CharField(blank=True, db_column='Themeneigentümer', max_length=150, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblOrga',
            },
        ),
        migrations.CreateModel(
            name='TblPlattform',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tf_technische_plattform', models.CharField(blank=True, db_column='TF Technische Plattform', max_length=150, null=True, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblPlattform',
            },
        ),
        migrations.CreateModel(
            name='TblUebersichtAfGfs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name_gf_neu', models.CharField(blank=True, db_column='Name GF Neu', max_length=50, null=True)),
                ('name_af_neu', models.CharField(db_column='Name AF Neu', max_length=50)),
                ('kommentar', models.CharField(blank=True, db_column='Kommentar', max_length=150, null=True)),
                ('zielperson', models.CharField(blank=True, db_column='Zielperson', max_length=50, null=True)),
                ('af_text', models.CharField(blank=True, db_column='AF Text', max_length=150, null=True)),
                ('gf_text', models.CharField(blank=True, db_column='GF Text', max_length=150, null=True)),
                ('af_langtext', models.CharField(blank=True, db_column='AF Langtext', max_length=150, null=True)),
                ('af_ausschlussgruppen', models.CharField(blank=True, db_column='AF Ausschlussgruppen', max_length=150, null=True)),
                ('af_einschlussgruppen', models.CharField(blank=True, db_column='AF Einschlussgruppen', max_length=150, null=True)),
                ('af_sonstige_vergabehinweise', models.CharField(blank=True, db_column='AF Sonstige Vergabehinweise', max_length=150, null=True)),
                ('geloescht', models.IntegerField(blank=True, db_column='gelöscht', null=True)),
                ('kannweg', models.IntegerField(blank=True, null=True)),
                ('modelliert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblÜbersichtAF_GFs',
            },
        ),
        migrations.CreateModel(
            name='TblUserIDundName',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='UserID', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=150, null=True)),
                ('zi_organisation', models.CharField(blank=True, db_column='ZI-Organisation', max_length=50, null=True)),
                ('geloescht', models.IntegerField(blank=True, db_column='gelöscht', null=True)),
                ('abteilung', models.CharField(blank=True, db_column='Abteilung', max_length=50, null=True)),
                ('gruppe', models.CharField(blank=True, db_column='Gruppe', max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tblUserIDundName',
            },
        ),
    ]
