# Generated by Django 2.1 on 2018-08-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_af_neu',
            field=models.CharField(blank=True, db_column='Name AF Neu', max_length=50, null=True, verbose_name='AF Neu'),
        ),
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_gf_neu',
            field=models.CharField(blank=True, db_column='Name GF Neu', max_length=50, null=True, verbose_name='GF Neu'),
        ),
    ]
