# Generated by Django 2.1 on 2018-08-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgesamt',
            name='enthalten_in_af',
            field=models.CharField(blank=True, db_column='Enthalten in AF', db_index=True, max_length=150, null=True, verbose_name='AF'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='userid_name',
            field=models.ForeignKey(blank=True, db_column='UserID + Name_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rapp.TblUserIDundName'),
        ),
        migrations.AlterField(
            model_name='tblgesamt',
            name='vip_kennzeichen',
            field=models.CharField(blank=True, db_column='VIP Kennzeichen', max_length=150, null=True, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_af_neu',
            field=models.CharField(blank=True, db_column='Name AF Neu', max_length=50, null=True, verbose_name='AF Neu'),
        ),
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_gf_neu',
            field=models.CharField(blank=True, db_column='Name GF Neu', max_length=50, null=True, verbose_name='GF Neu'),
        ),
    ]
