# Generated by Django 2.0.7 on 2018-08-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAfliste',
            fields=[
                ('af_name', models.CharField(db_column='AF-Name', max_length=150, primary_key=True, serialize=False, verbose_name='AF-Name')),
                ('neu_ab', models.DateTimeField(db_column='neu ab')),
            ],
            options={
                'managed': False,
                'ordering': ['af_name'],
                'verbose_name_plural': 'Übersicht gültiger AFen (tbl_AFListe)',
                'db_table': 'tbl_AFListe',
                'verbose_name': 'Gültige AF',
            },
        ),
        migrations.CreateModel(
            name='TblRollehataf',
            fields=[
                ('rollenmappingid', models.AutoField(db_column='RollenMappingID', primary_key=True, serialize=False)),
                ('mussfeld', models.TextField(blank=True, db_column='Mussfeld', null=True, verbose_name='Muss')),
                ('bemerkung', models.CharField(blank=True, db_column='Bemerkung', max_length=150, null=True)),
                ('nurxv', models.TextField(blank=True, db_column='nurXV', null=True)),
                ('xabcv', models.TextField(blank=True, db_column='XABCV', null=True)),
                ('dv', models.TextField(blank=True, db_column='DV', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_RolleHatAF',
            },
        ),
        migrations.CreateModel(
            name='TblUserhatrolle',
            fields=[
                ('userundrollenid', models.AutoField(db_column='UserUndRollenID', primary_key=True, serialize=False)),
                ('schwerpunkt_vertretung', models.CharField(blank=True, db_column='Schwerpunkt/Vertretung', max_length=150, null=True)),
                ('bemerkung', models.CharField(blank=True, db_column='Bemerkung', max_length=150, null=True)),
                ('letzte_aenderung', models.DateTimeField(db_column='Letzte Änderung')),
            ],
            options={
                'managed': False,
                'db_table': 'tbl_UserHatRolle',
            },
        ),
        migrations.AlterModelOptions(
            name='tblgesamt',
            options={'managed': False, 'verbose_name': 'Eintrag der Gesamttabelle (tblGesamt)', 'verbose_name_plural': 'Gesamttabelle Übersicht (tblGesamt)'},
        ),
        migrations.AlterModelOptions(
            name='tblorga',
            options={'managed': True, 'ordering': ['team'], 'verbose_name': 'Orga-Information', 'verbose_name_plural': 'Organisations-Übersicht (tblOrga)'},
        ),
        migrations.AlterModelOptions(
            name='tblplattform',
            options={'managed': False, 'verbose_name': 'Plattform', 'verbose_name_plural': 'Plattform-Übersicht (tblPlattform)'},
        ),
        migrations.AlterModelOptions(
            name='tbluebersichtafgfs',
            options={'managed': False, 'ordering': ['-id'], 'verbose_name': 'Erlaubte AF/GF-Kombination', 'verbose_name_plural': 'Erlaubte AF/GF-Kombinationen-Übersicht (tblUebersichtAfGfs)'},
        ),
        migrations.AlterModelOptions(
            name='tbluseridundname',
            options={'managed': False, 'ordering': ['geloescht', 'name', '-userid'], 'verbose_name': 'UserID-Name-Kombination', 'verbose_name_plural': 'UserID-Name-Übersicht (tblUserIDundName)'},
        ),
    ]
