# Generated by Django 2.1 on 2018-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20180818_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblrechteamneu',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.CharField(blank=True, db_column='UserID', db_index=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', db_index=True, max_length=150, null=True)),
                ('tf', models.CharField(blank=True, db_column='TF', db_index=True, max_length=150, null=True)),
                ('tf_beschreibung', models.CharField(blank=True, db_column='TF Beschreibung', db_index=True, max_length=500, null=True)),
                ('enthalten_in_af', models.CharField(blank=True, db_column='Enthalten in AF', db_index=True, max_length=150, null=True)),
                ('tf_kritikalität', models.CharField(blank=True, db_column='TF Kritikalität', max_length=150, null=True)),
                ('tf_eigentümer_org', models.CharField(blank=True, db_column='TF Eigentümer Org', db_index=True, max_length=150, null=True)),
                ('tf_technische_plattform', models.CharField(blank=True, db_column='TF Technische Plattform', db_index=True, max_length=150, null=True)),
                ('gf', models.CharField(blank=True, db_column='GF', db_index=True, max_length=150, null=True)),
                ('vip_kennzeichen', models.CharField(blank=True, db_column='VIP Kennzeichen', db_index=True, max_length=150, null=True)),
                ('zufallsgenerator', models.CharField(blank=True, db_column='Zufallsgenerator', db_index=True, max_length=150, null=True)),
                ('af_gültig_ab', models.DateTimeField(blank=True, db_column='AF Gültig ab', null=True)),
                ('af_gültig_bis', models.DateTimeField(blank=True, db_column='AF Gültig bis', null=True)),
                ('direct_connect', models.CharField(blank=True, db_column='Direct Connect', max_length=150, null=True)),
                ('höchste_kritikalität_tf_in_af', models.CharField(blank=True, db_column='Höchste Kritikalität TF in AF', db_index=True, max_length=150, null=True)),
                ('gf_beschreibung', models.CharField(blank=True, db_column='GF Beschreibung', max_length=250, null=True)),
                ('af_zuweisungsdatum', models.DateTimeField(blank=True, db_column='AF Zuweisungsdatum', null=True)),
                ('gefunden', models.IntegerField(blank=True, db_column='Gefunden', db_index=True, null=True)),
                ('geändert', models.IntegerField(blank=True, db_column='Geändert', db_index=True, null=True)),
                ('angehängtbekannt', models.IntegerField(blank=True, db_column='angehängtBekannt', db_index=True, null=True)),
                ('angehängtsonst', models.IntegerField(blank=True, db_column='angehängtSonst', db_index=True, null=True)),
                ('doppelerkennung', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblRechteAMNeu',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='tblorga',
            name='team',
            field=models.CharField(db_column='Intern - extern', db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tblorga',
            name='themeneigentuemer',
            field=models.CharField(db_column='Themeneigentümer', db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tblplattform',
            name='tf_technische_plattform',
            field=models.CharField(blank=True, db_column='TF Technische Plattform', db_index=True, max_length=32, null=True, unique=True, verbose_name='Plattform'),
        ),
        migrations.AlterField(
            model_name='tblrechteneuvonimport',
            name='gf_beschreibung',
            field=models.CharField(blank=True, db_column='GF Beschreibung', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteneuvonimport',
            name='tf_beschreibung',
            field=models.CharField(blank=True, db_column='TF Beschreibung', max_length=500, null=True),
        ),
    ]
