# Generated by Django 2.1 on 2018-08-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20180818_1113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblgesamthistorie',
            table='tblGesamtHistorie',
        ),
    ]
