# Generated by Django 2.0.7 on 2018-08-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0002_auto_20180801_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbluserhatrolle',
            options={'managed': False, 'ordering': ['userid__name', '-userid__userid', 'schwerpunkt_vertretung', 'rollenname'], 'verbose_name': 'User und Ihre Rollen', 'verbose_name_plural': 'User und Ihre Rollen (tbl_UserHatRolle)'},
        ),
        migrations.AlterField(
            model_name='tblorga',
            name='team',
            field=models.CharField(db_column='Intern - extern', default='Hä???', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tblorga',
            name='themeneigentuemer',
            field=models.CharField(db_column='Themeneigentümer', default='Hä???', max_length=150),
        ),
    ]
