# Generated by Django 2.1 on 2018-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_auto_20180818_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluseridundname',
            name='geloescht',
            field=models.IntegerField(blank=True, db_column='gelöscht', db_index=True, null=True, verbose_name='gelöscht'),
        ),
        migrations.AlterField(
            model_name='tbluseridundname',
            name='gruppe',
            field=models.CharField(blank=True, db_column='Gruppe', db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbluseridundname',
            name='zi_organisation',
            field=models.CharField(blank=True, db_column='ZI-Organisation', db_index=True, max_length=50, null=True, verbose_name='ZI-Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='tbluseridundname',
            unique_together={('userid', 'name'), ('userid', 'name', 'gruppe', 'orga', 'geloescht'), ('gruppe', 'orga', 'geloescht'), ('gruppe', 'geloescht')},
        ),
    ]
