# Generated by Django 2.0.7 on 2018-08-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_tblgesamthistorie_tblrollen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblrollehataf',
            options={'managed': False, 'ordering': ['rollenname__rollenname', 'afname__af_name'], 'verbose_name': 'Rolle und ihre Arbeitsplatzfunktionen', 'verbose_name_plural': 'Rollen und ihre Arbeitsplatzfunktionen (tbl_RolleHatAF)'},
        ),
    ]
