# Generated by Django 2.1 on 2018-08-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_auto_20180818_1235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbluseridundname',
            unique_together={('userid', 'name', 'gruppe', 'orga', 'geloescht'), ('userid', 'name'), ('gruppe', 'orga', 'geloescht'), ('gruppe', 'geloescht')},
        ),
    ]
