# Generated by Django 2.0.7 on 2018-08-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_auto_20180803_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblafliste',
            options={'managed': True, 'ordering': ['af_name'], 'verbose_name': 'Gültige AF', 'verbose_name_plural': 'Übersicht gültiger AFen (tbl_AFListe)'},
        ),
    ]
