# Generated by Django 2.1 on 2018-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_auto_20180818_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluseridundname',
            name='zi_organisation',
            field=models.CharField(blank=True, db_column='ZI_Organisation', db_index=True, max_length=50, null=True, verbose_name='ZI-Organisation'),
        ),
    ]
