# Generated by Django 2.0.7 on 2018-08-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0006_auto_20180803_1131'),
    ]

    operations = [
    ]
