# Generated by Django 2.1 on 2018-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0007_auto_20180818_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluseridundname',
            name='zi_organisation',
            field=models.CharField(blank=True, db_column='ZI-Organisation', db_index=True, max_length=50, null=True, verbose_name='ZI-Organisation'),
        ),
    ]
