# Generated by Django 2.0.7 on 2018-08-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0008_auto_20180803_1321'),
    ]

    operations = [
    ]
