# Generated by Django 2.0.7 on 2018-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0010_auto_20180803_1322'),
    ]

    operations = [
    ]
