# Generated by Django 2.1 on 2018-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0011_auto_20180818_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrollen',
            name='system',
            field=models.CharField(db_column='System', db_index=True, max_length=150, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='tbluserhatrolle',
            name='letzte_aenderung',
            field=models.DateTimeField(db_column='Letzte Änderung', db_index=True),
        ),
        migrations.AlterField(
            model_name='tbluserhatrolle',
            name='schwerpunkt_vertretung',
            field=models.CharField(blank=True, choices=[('Schwerpunkt', 'Schwerpunktaufgabe'), ('Vertretung', 'Vertretungstätigkeiten, Zweitsysteme'), ('Allgemein', 'Rollen, die nicht Systemen zugeordnet sind')], db_column='Schwerpunkt/Vertretung', db_index=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tblrollen',
            unique_together={('rollenname', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='tbluserhatrolle',
            unique_together={('userid', 'rollenname')},
        ),
    ]
