# Generated by Django 2.0.7 on 2018-08-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0012_auto_20180803_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblDb2',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('geloescht', models.TextField(blank=True, db_column='gelöscht', null=True)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=15, null=True)),
                ('creator', models.CharField(blank=True, db_column='CREATOR', max_length=15, null=True)),
                ('table', models.CharField(db_column='TABLE', max_length=31)),
                ('selectauth', models.CharField(blank=True, db_column='SELECTAUTH', max_length=3, null=True)),
                ('insertauth', models.CharField(blank=True, db_column='INSERTAUTH', max_length=3, null=True)),
                ('updateauth', models.CharField(blank=True, db_column='UPDATEAUTH', max_length=3, null=True)),
                ('deleteauth', models.CharField(blank=True, db_column='DELETEAUTH', max_length=3, null=True)),
                ('alterauth', models.CharField(blank=True, db_column='ALTERAUTH', max_length=3, null=True)),
                ('indexauth', models.CharField(blank=True, db_column='INDEXAUTH', max_length=3, null=True)),
                ('grantor', models.CharField(db_column='GRANTOR', max_length=15)),
                ('grantedts', models.CharField(db_column='GRANTEDTS', max_length=63)),
                ('datum', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'DB2-Berechtigung',
                'db_table': 'tbl_DB2',
                'verbose_name_plural': 'DB2 - Berechtigungen (tbl_DB2)',
                'managed': False,
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TblRacfGruppen',
            fields=[
                ('group', models.CharField(db_column='Group', max_length=150, primary_key=True, serialize=False)),
                ('test', models.IntegerField(blank=True, db_column='Test', null=True)),
                ('produktion', models.IntegerField(blank=True, db_column='Produktion', null=True)),
                ('readonly', models.IntegerField(blank=True, db_column='Readonly', null=True)),
                ('db2_only', models.IntegerField(blank=True, db_column='DB2-only', null=True)),
                ('stempel', models.DateTimeField(db_column='Stempel')),
            ],
            options={
                'verbose_name': 'RACF-Berechtigung',
                'db_table': 'tbl_RACF_Gruppen',
                'verbose_name_plural': 'RACF - Berechtigungen (tbl_DB2)',
                'managed': False,
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Tblsachgebiete',
            fields=[
                ('sachgebiet', models.CharField(db_column='Sachgebiet', max_length=150, primary_key=True, serialize=False)),
                ('definition_field', models.CharField(blank=True, db_column='Definition\xa0', max_length=150, null=True)),
                ('verantwortlicher_field', models.CharField(blank=True, db_column='Verantwortlicher\xa0', max_length=150, null=True)),
                ('telefon_verantwortlicher_field', models.CharField(blank=True, db_column='Telefon(Verantwortlicher)\xa0', max_length=150, null=True)),
                ('user_id_verantwortlicher_field', models.CharField(blank=True, db_column='User-ID(Verantwortlicher)\xa0', max_length=150, null=True)),
                ('führungskraft_field', models.CharField(blank=True, db_column='Führungskraft\xa0', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Sachgebiet',
                'db_table': 'tblSachgebiete',
                'verbose_name_plural': 'Übersicht Sachgebiete (tbl_Sachgebiete)',
                'managed': False,
                'ordering': ['sachgebiet'],
            },
        ),
        migrations.CreateModel(
            name='Tblsubsysteme',
            fields=[
                ('sgss', models.CharField(db_column='SGSS', max_length=150, primary_key=True, serialize=False)),
                ('definition_field', models.CharField(blank=True, db_column='Definition\xa0', max_length=150, null=True)),
                ('verantwortlicher_field', models.CharField(blank=True, db_column='Verantwortlicher\xa0', max_length=150, null=True)),
                ('telefon_verantwortlicher_field', models.CharField(blank=True, db_column='Telefon(Verantwortlicher)\xa0', max_length=150, null=True)),
                ('user_id_verantwortlicher_field', models.CharField(blank=True, db_column='User-ID(Verantwortlicher)\xa0', max_length=150, null=True)),
                ('führungskraft_field', models.CharField(blank=True, db_column='Führungskraft\xa0', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Subsystem',
                'db_table': 'tblSubsysteme',
                'verbose_name_plural': 'Übersicht Subsysteme (tbl_Subsysteme)',
                'managed': False,
                'ordering': ['sgss'],
            },
        ),
    ]
