# Generated by Django 2.1 on 2018-08-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0012_auto_20180818_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='geloescht',
            field=models.IntegerField(blank=True, db_column='gelöscht', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_af_neu',
            field=models.CharField(blank=True, db_column='Name AF Neu', db_index=True, max_length=50, null=True, verbose_name='AF Neu'),
        ),
        migrations.AlterField(
            model_name='tbluebersichtafgfs',
            name='name_gf_neu',
            field=models.CharField(blank=True, db_column='Name GF Neu', db_index=True, max_length=50, null=True, verbose_name='GF Neu'),
        ),
    ]
