# Generated by Django 2.1 on 2018-08-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0013_auto_20180818_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrollehataf',
            name='af',
            field=models.ForeignKey(blank=True, db_column='AF', null=True, on_delete=django.db.models.deletion.PROTECT, to='rapp.TblAfliste', verbose_name='AF'),
        ),
        migrations.AlterField(
            model_name='tblrollehataf',
            name='afname',
            field=models.CharField(db_column='AFName', max_length=150, verbose_name='AF Name'),
        ),
    ]
