# Generated by Django 2.0.7 on 2018-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0013_tbldb2_tblracfgruppen_tblsachgebiete_tblsubsysteme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblrechteneuvonimport',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('identitaet', models.CharField(db_column='Identität', db_index=True, max_length=150)),
                ('nachname', models.CharField(blank=True, db_column='Nachname', max_length=150, null=True)),
                ('vorname', models.CharField(blank=True, db_column='Vorname', max_length=150, null=True)),
                ('tf_name', models.CharField(blank=True, db_column='TF Name', max_length=150, null=True)),
                ('tf_beschreibung', models.CharField(blank=True, db_column='TF Beschreibung', max_length=150, null=True)),
                ('af_anzeigename', models.CharField(blank=True, db_column='AF Anzeigename', max_length=150, null=True)),
                ('af_beschreibung', models.CharField(blank=True, db_column='AF Beschreibung', max_length=150, null=True)),
                ('hoechste_kritikalitaet_tf_in_af', models.CharField(blank=True, db_column='Höchste Kritikalität TF in AF', max_length=150, null=True)),
                ('tf_eigentuemer_org', models.CharField(blank=True, db_column='TF Eigentümer Org', max_length=150, null=True)),
                ('tf_applikation', models.CharField(blank=True, db_column='TF Applikation', max_length=150, null=True)),
                ('tf_kritikalitaet', models.CharField(blank=True, db_column='TF Kritikalität', max_length=150, null=True)),
                ('gf_name', models.CharField(blank=True, db_column='GF Name', max_length=150, null=True)),
                ('gf_beschreibung', models.CharField(blank=True, db_column='GF Beschreibung', max_length=150, null=True)),
                ('direct_connect', models.CharField(blank=True, db_column='Direct Connect', max_length=150, null=True)),
                ('af_zugewiesen_an_account_name', models.CharField(blank=True, db_column='AF zugewiesen an Account-Name', max_length=150, null=True)),
                ('af_gueltig_ab', models.DateTimeField(blank=True, db_column='AF Gültig ab', null=True)),
                ('af_gueltig_bis', models.DateTimeField(blank=True, db_column='AF Gültig bis', null=True)),
                ('af_zuweisungsdatum', models.DateTimeField(blank=True, db_column='AF Zuweisungsdatum', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'tblRechteNeuVonImport',
            },
        ),
    ]
