# Generated by Django 2.1 on 2018-08-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0014_auto_20180818_1551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblrollehataf',
            table='tbl_RolleHatAF',
        ),
    ]
