# Generated by Django 2.1 on 2018-08-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0015_auto_20180818_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='userid_name',
            field=models.ForeignKey(db_column='UserID + Name_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.TblUserIDundName'),
        ),
    ]
