# Generated by Django 2.1 on 2018-08-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0016_auto_20180818_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='id_alt',
            field=models.ForeignKey(db_column='ID-alt', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.TblGesamt'),
        ),
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='modell',
            field=models.ForeignKey(db_column='Modell', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.TblUebersichtAfGfs'),
        ),
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='plattform',
            field=models.ForeignKey(db_column='Plattform_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='rapp.TblPlattform'),
        ),
    ]
