# Generated by Django 2.1 on 2018-08-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0017_auto_20180818_1721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tbluseridundname',
            unique_together={('userid', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='tbluseridundname',
            index_together={('gruppe', 'geloescht')},
        ),
    ]
