# Generated by Django 2.1 on 2018-08-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0018_auto_20180818_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblgesamt',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='tblgesamt',
            index_together={('userid_name', 'tf', 'enthalten_in_af', 'plattform', 'gf', 'vip_kennzeichen', 'zufallsgenerator')},
        ),
    ]
