# Generated by Django 2.1 on 2018-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0019_auto_20180818_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblgesamthistorie',
            name='id_alt',
            field=models.IntegerField(db_column='ID-alt', db_index=True),
        ),
    ]
