# Generated by Django 2.1 on 2018-08-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0021_auto_20180818_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblafliste',
            options={'managed': True, 'ordering': ['af_name'], 'verbose_name': 'Gültige AF', 'verbose_name_plural': '98 Übersicht gültiger AFen (tbl_AFListe)'},
        ),
        migrations.AlterModelOptions(
            name='tbldb2',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'DB2-Berechtigung', 'verbose_name_plural': '52 DB2 - Berechtigungen (tbl_DB2)'},
        ),
        migrations.AlterModelOptions(
            name='tblgesamt',
            options={'managed': True, 'verbose_name': 'Eintrag der Gesamttabelle (tblGesamt)', 'verbose_name_plural': '08 Gesamttabelle Übersicht (tblGesamt)'},
        ),
        migrations.AlterModelOptions(
            name='tblgesamthistorie',
            options={'managed': True, 'verbose_name': 'Historisierter Eintrag der Gesamttabelle (tblGesamtHistorie)', 'verbose_name_plural': '99 Historisierte Einträge der Gesamttabelle (tblGesamtHistorie)'},
        ),
        migrations.AlterModelOptions(
            name='tblorga',
            options={'managed': True, 'ordering': ['team'], 'verbose_name': 'Orga-Information', 'verbose_name_plural': '06 Organisations-Übersicht (tblOrga)'},
        ),
        migrations.AlterModelOptions(
            name='tblplattform',
            options={'managed': True, 'verbose_name': 'Plattform', 'verbose_name_plural': '07 Plattform-Übersicht (tblPlattform)'},
        ),
        migrations.AlterModelOptions(
            name='tblracfgruppen',
            options={'managed': True, 'ordering': ['group'], 'verbose_name': 'RACF-Berechtigung', 'verbose_name_plural': '53 RACF - Berechtigungen (tbl_DB2)'},
        ),
        migrations.AlterModelOptions(
            name='tblrollehataf',
            options={'managed': True, 'ordering': ['rollenname__rollenname', 'af__af_name'], 'verbose_name': 'Rolle und ihre Arbeitsplatzfunktionen', 'verbose_name_plural': '02 Rollen und ihre Arbeitsplatzfunktionen (tbl_RolleHatAF)'},
        ),
        migrations.AlterModelOptions(
            name='tblrollen',
            options={'managed': True, 'ordering': ['rollenname'], 'verbose_name': 'Rollenliste', 'verbose_name_plural': '03 Rollen-Übersicht (tbl_Rollen)'},
        ),
        migrations.AlterModelOptions(
            name='tblsachgebiete',
            options={'managed': True, 'ordering': ['sachgebiet'], 'verbose_name': 'Sachgebiet', 'verbose_name_plural': '51 Übersicht Sachgebiete (tbl_Sachgebiete)'},
        ),
        migrations.AlterModelOptions(
            name='tblsubsysteme',
            options={'managed': True, 'ordering': ['sgss'], 'verbose_name': 'Subsystem', 'verbose_name_plural': '50 Übersicht Subsysteme (tbl_Subsysteme)'},
        ),
        migrations.AlterModelOptions(
            name='tbluebersichtafgfs',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Erlaubte AF/GF-Kombination', 'verbose_name_plural': '04 Erlaubte AF/GF-Kombinationen-Übersicht (tblUebersichtAfGfs)'},
        ),
        migrations.AlterModelOptions(
            name='tbluserhatrolle',
            options={'managed': True, 'ordering': ['userid__name', '-userid__userid', 'schwerpunkt_vertretung', 'rollenname'], 'verbose_name': 'User und Ihre Rollen', 'verbose_name_plural': '01 User und Ihre Rollen (tbl_UserHatRolle)'},
        ),
        migrations.AlterModelOptions(
            name='tbluseridundname',
            options={'managed': True, 'ordering': ['geloescht', 'name', '-userid'], 'verbose_name': 'UserID-Name-Kombination', 'verbose_name_plural': '05 UserID-Name-Übersicht (tblUserIDundName)'},
        ),
    ]
