# Generated by Django 2.1 on 2018-08-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0022_auto_20180818_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qryf3Rechteneuvonimportduplikatfrei',
            fields=[
                ('userid', models.CharField(db_column='UserID', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=202, null=True)),
                ('tf', models.CharField(db_column='TF', max_length=100)),
                ('tf_beschreibung', models.CharField(blank=True, db_column='TF Beschreibung', max_length=500, null=True)),
                ('enthalten_in_af', models.CharField(db_column='Enthalten in AF', max_length=100)),
                ('tf_kritikalitaet', models.CharField(blank=True, db_column='TF Kritikalität', max_length=50, null=True)),
                ('tf_eigentuemer_org', models.CharField(blank=True, db_column='TF Eigentümer Org', max_length=50, null=True)),
                ('tf_technische_plattform', models.CharField(db_column='TF Technische Plattform', max_length=50)),
                ('gf', models.CharField(db_column='GF', max_length=50)),
                ('vip_kennzeichen', models.CharField(db_column='VIP Kennzeichen', max_length=18)),
                ('zufallsgenerator', models.CharField(db_column='Zufallsgenerator', max_length=18)),
                ('af_gueltig_ab', models.DateTimeField(blank=True, db_column='AF Gültig ab', null=True)),
                ('af_gueltig_bis', models.DateTimeField(blank=True, db_column='AF Gültig bis', null=True)),
                ('direct_connect', models.CharField(blank=True, db_column='Direct Connect', max_length=50, null=True)),
                ('hoechste_kritikalitaet_tf_in_af', models.CharField(blank=True, db_column='Höchste Kritikalität TF in AF', max_length=50, null=True)),
                ('gf_beschreibung', models.CharField(blank=True, db_column='GF Beschreibung', max_length=250, null=True)),
                ('af_zuweisungsdatum', models.DateTimeField(blank=True, db_column='AF Zuweisungsdatum', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'qryF3_RechteNeuVonImportDuplikatfrei',
            },
        ),
    ]
