# Generated by Django 2.1 on 2018-08-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0023_qryf3rechteneuvonimportduplikatfrei'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qryf3rechteneuvonimportduplikatfrei',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblrechteamneu',
            options={'managed': True},
        ),
    ]
