# Generated by Django 2.1 on 2018-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0026_auto_20180819_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='af_gültig_ab',
            field=models.DateTimeField(blank=True, db_column='AF Gültig ab', null=True),
        ),
        migrations.AddField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='af_gültig_bis',
            field=models.DateTimeField(blank=True, db_column='AF Gültig bis', null=True),
        ),
        migrations.AddField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='höchste_kritikalität_tf_in_af',
            field=models.CharField(blank=True, db_column='Höchste Kritikalität TF in AF', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='tf_eigentümer_org',
            field=models.CharField(blank=True, db_column='TF Eigentümer Org', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='tf_kritikalität',
            field=models.CharField(blank=True, db_column='TF Kritikalität', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblgesamthistorie',
            name='af_zuweisungsdatum',
            field=models.DateTimeField(blank=True, db_column='AF Zuweisungsdatum', db_index=True, null=True, verbose_name='AF Zuweisung'),
        ),
        migrations.RemoveField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='af_gueltig_ab',
        ),
        migrations.RemoveField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='af_gueltig_bis',
        ),
        migrations.RemoveField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='hoechste_kritikalitaet_tf_in_af',
        ),
        migrations.RemoveField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='tf_eigentuemer_org',
        ),
        migrations.RemoveField(
            model_name='qryf3rechteneuvonimportduplikatfrei',
            name='tf_kritikalitaet',
        ),
    ]
