# Generated by Django 2.1 on 2018-08-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0029_auto_20180819_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblrechteamneu',
            unique_together=set(),
        ),
    ]
