# Generated by Django 2.1 on 2018-08-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0030_auto_20180819_1056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblrechteamneu',
            unique_together={('userid', 'tf', 'enthalten_in_af', 'tf_technische_plattform', 'gf')},
        ),
    ]
