# Generated by Django 2.1 on 2018-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0031_auto_20180819_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='enthalten_in_af',
            field=models.CharField(blank=True, db_column='Enthalten in AF', db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tblrechteamneu',
            name='tf_technische_plattform',
            field=models.CharField(blank=True, db_column='TF Technische Plattform', db_index=True, max_length=150, null=True),
        ),
    ]
